"""Agentic Architectures 1: Reflection.

A reflective agent that generates an initial draft, critiques it, and refines
the code based on the critique. Uses Google Gemini via LangChain and LangGraph.
"""

import json
import os
import time
from typing import List, Optional, TypedDict

import requests
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field
from rich.console import Console
from rich.markdown import Markdown
from rich.syntax import Syntax


# --- API Key and Tracing Setup ---
load_dotenv(override=True)

os.environ["LANGCHAIN_PROJECT"] = "Agentic Architecture - Reflection (Gemini)"

api_key = os.getenv("GOOGLE_API_KEY")
print(f"GOOGLE_API_KEY: {repr(api_key)}")
print(f"LANGCHAIN_API_KEY: {repr(os.getenv('LANGCHAIN_API_KEY'))}")

url = "https://generativelanguage.googleapis.com/v1beta/models"
headers = {"X-goog-api-key": api_key}
response = requests.get(url, headers=headers)
print(response.json())

if not os.environ.get("GOOGLE_API_KEY"):
    print("GOOGLE_API_KEY not found. Please create a .env file and set it.")
else:
    print("GOOGLE_API_KEY found: ", os.environ.get("GOOGLE_API_KEY"))
if not os.environ.get("LANGCHAIN_API_KEY"):
    print("LANGCHAIN_API_KEY not found. Please create a .env file and set it for tracing.")
else:
    print("LANGCHAIN_API_KEY found: ", os.environ.get("LANGCHAIN_API_KEY"))

print("Environment variables loaded and tracing is set up.")


# --- Pydantic Schemas ---
class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""

    code: str = Field(description="The Python code generated to solve the user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")


class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""

    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(
        description="Specific, actionable suggestions for improving the code."
    )
    critique_summary: str = Field(description="A summary of the critique.")


class RefinedCode(BaseModel):
    """Schema for the final, refined code after incorporating the critique."""

    refined_code: str = Field(description="The final, improved Python code.")
    refinement_summary: str = Field(
        description="A summary of the changes made based on the critique."
    )


class CodeEvaluation(BaseModel):
    """Schema for evaluating a piece of code."""

    correctness_score: int = Field(
        description="Score from 1-10 on whether the code is logically correct."
    )
    efficiency_score: int = Field(
        description="Score from 1-10 on the code's algorithmic efficiency."
    )
    style_score: int = Field(
        description="Score from 1-10 on code style and readability (PEP 8)."
    )
    justification: str = Field(description="A brief justification for the scores.")


print("Pydantic models for Draft, Critique, and RefinedCode have been defined.")


# --- LLM and Console ---
llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite-preview", temperature=0.2)
console = Console()
print("Gemini LLM and Console are initialized.")


def _invoke_with_retry(structured_llm, prompt: str, max_attempts: int = 3):
    """Invoke a structured LLM with small retry/backoff for transient API errors (e.g. 503).

    The Gemini API can intermittently return 503 UNAVAILABLE under load. Without
    retry, a single transient failure crashes the whole graph; this wrapper
    retries with linear backoff (2s, 4s, ...) before giving up.
    """
    last_exc: Optional[BaseException] = None
    for attempt in range(1, max_attempts + 1):
        try:
            return structured_llm.invoke(prompt)
        except Exception as e:
            last_exc = e
            if attempt >= max_attempts:
                break
            wait = 2 * attempt
            console.print(
                f"[yellow]LLM call failed ({type(e).__name__}); "
                f"retrying in {wait}s (attempt {attempt}/{max_attempts})...[/yellow]"
            )
            time.sleep(wait)
    assert last_exc is not None
    raise last_exc


# --- Graph Nodes ---
def generator_node(state):
    """Generates the initial draft of the code."""
    console.print("--- 1. Generating Initial Draft ---")
    generator_llm = llm.with_structured_output(DraftCode)

    prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation and an explanation.

    Request: {state['user_request']}
    """

    draft = _invoke_with_retry(generator_llm, prompt)
    return {"draft": draft.model_dump()}


def critic_node(state):
    """Critiques the generated code for errors and inefficiencies."""
    console.print("--- 2. Critiquing Draft ---")
    critic_llm = llm.with_structured_output(Critique)

    code_to_critique = state["draft"]["code"]

    prompt = f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.

    Analyze the code for:
    1.  **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
    2.  **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?

    Provide a structured critique with specific, actionable suggestions.

    Code to Review:
    ```python
    {code_to_critique}
    ```
    """

    critique = _invoke_with_retry(critic_llm, prompt)
    return {"critique": critique.model_dump()}


def refiner_node(state):
    """Refines the code based on the critique."""
    console.print("--- 3. Refining Code ---")
    refiner_llm = llm.with_structured_output(RefinedCode)

    draft_code = state["draft"]["code"]
    critique_suggestions = json.dumps(state["critique"], indent=2)

    prompt = f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.

    Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.

    **Original Code:**
    ```python
    {draft_code}
    ```

    **Critique and Suggestions:**
    {critique_suggestions}

    Please provide the final, refined code and a summary of the changes you made.
    """

    refined_code = _invoke_with_retry(refiner_llm, prompt)
    return {"refined_code": refined_code.model_dump()}


# --- Graph State ---
class ReflectionState(TypedDict):
    """Represents the state of our reflection graph."""

    user_request: str
    draft: Optional[dict]
    critique: Optional[dict]
    refined_code: Optional[dict]


print("ReflectionState TypedDict defined.")


# --- Build the Graph ---
graph_builder = StateGraph(ReflectionState)

graph_builder.add_node("generator", generator_node)
graph_builder.add_node("critic", critic_node)
graph_builder.add_node("refiner", refiner_node)

graph_builder.set_entry_point("generator")
graph_builder.add_edge("generator", "critic")
graph_builder.add_edge("critic", "refiner")
graph_builder.add_edge("refiner", END)

reflection_app = graph_builder.compile()
print("Reflection graph compiled successfully!")


# --- Evaluation Helper ---
judge_llm = llm.with_structured_output(CodeEvaluation)


def evaluate_code(code_to_evaluate: str):
    """Use an LLM-as-a-judge to score the given code."""
    prompt = f"""You are an expert judge of Python code. Evaluate the following function on a scale of 1-10 for correctness, efficiency, and style. Provide a brief justification.

    Code:
    ```python
    {code_to_evaluate}
    ```
    """
    return judge_llm.invoke(prompt)


def main():
    """Run the reflection workflow end-to-end and print the results."""
    user_request = """You have this URL:
https://generativelanguage.googleapis.com/v1beta/models" -H "X-goog-api-key: $GOOGLE_API_KEY"
Give me a code that will make a request to this URL and print the response.
"""
    initial_input : ReflectionState = {"user_request": user_request}

    console.print(
        f"[bold cyan]🚀 Kicking off Reflection workflow for request:[/bold cyan] '{user_request}'\n"
    )

    final_state : Optional[ReflectionState] = None
    for state_update in reflection_app.stream(initial_input, stream_mode="values"):
        final_state = state_update

    console.print("\n[bold green]✅ Reflection workflow complete![/bold green]")

    if (
        final_state
        and "draft" in final_state
        and "critique" in final_state
        and "refined_code" in final_state
    ):
        console.print(Markdown("--- ### Initial Draft ---"))
        console.print(Markdown(f"**Explanation:** {final_state['draft']['explanation']}"))
        console.print(
            Syntax(final_state["draft"]["code"], "python", theme="monokai", line_numbers=True)
        )

        console.print(Markdown("\n--- ### Critique ---"))
        console.print(Markdown(f"**Summary:** {final_state['critique']['critique_summary']}"))
        console.print(Markdown("**Improvements Suggested:**"))
        for improvement in final_state["critique"]["suggested_improvements"]:
            console.print(Markdown(f"- {improvement}"))

        console.print(Markdown("\n--- ### Final Refined Code ---"))
        console.print(
            Markdown(
                f"**Refinement Summary:** {final_state['refined_code']['refinement_summary']}"
            )
        )
        console.print(
            Syntax(
                final_state["refined_code"]["refined_code"],
                "python",
                theme="monokai",
                line_numbers=True,
            )
        )

        console.print("--- Evaluating Initial Draft ---")
        initial_draft_evaluation = evaluate_code(final_state["draft"]["code"])
        console.print(initial_draft_evaluation.model_dump())

        console.print("\n--- Evaluating Refined Code ---")
        refined_code_evaluation = evaluate_code(final_state["refined_code"]["refined_code"])
        console.print(refined_code_evaluation.model_dump())
    else:
        console.print(
            "[bold red]Error: The `final_state` is not available or is incomplete.[/bold red]"
        )


if __name__ == "__main__":
    main()
