"""Agentic Architectures 1: Reflection (Streamlit UI).

A reflective agent that generates an initial draft, critiques it, and refines
the code based on the critique. Uses Google Gemini via LangChain and LangGraph.

Run with:
    streamlit run 01_reflection.py
"""

import json
import os
import time
from typing import List, Optional, TypedDict

import requests
import streamlit as st
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field


# --- API Key and Tracing Setup ---
load_dotenv(override=True)
os.environ["LANGCHAIN_TRACING_V2"] = "false"
os.environ["LANGCHAIN_PROJECT"] = "Agentic Architecture - Reflection (Gemini)"


# --- Pydantic Schemas ---
class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""

    code: str = Field(description="The Python code generated to solve the user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")


class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""

    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(
        description="Specific, actionable suggestions for improving the code."
    )
    critique_summary: str = Field(description="A summary of the critique.")


class RefinedCode(BaseModel):
    """Schema for the final, refined code after incorporating the critique."""

    refined_code: str = Field(description="The final, improved Python code.")
    refinement_summary: str = Field(
        description="A summary of the changes made based on the critique."
    )


class CodeEvaluation(BaseModel):
    """Schema for evaluating a piece of code."""

    correctness_score: int = Field(
        description="Score from 1-10 on whether the code is logically correct."
    )
    efficiency_score: int = Field(
        description="Score from 1-10 on the code's algorithmic efficiency."
    )
    style_score: int = Field(
        description="Score from 1-10 on code style and readability (PEP 8)."
    )
    justification: str = Field(description="A brief justification for the scores.")


# --- Graph State ---
class ReflectionState(TypedDict):
    """Represents the state of our reflection graph."""

    user_request: str
    draft: Optional[dict]
    critique: Optional[dict]
    refined_code: Optional[dict]


# --- LLM helpers ---
@st.cache_resource(show_spinner=False)
def get_llm() -> ChatGoogleGenerativeAI:
    """Return a cached Gemini LLM client."""
    return ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite-preview", temperature=0.2)


def _invoke_with_retry(structured_llm, prompt: str, max_attempts: int = 3):
    """Invoke a structured LLM with small retry/backoff for transient API errors (e.g. 503).

    The Gemini API can intermittently return 503 UNAVAILABLE under load. Without
    retry, a single transient failure crashes the whole graph; this wrapper
    retries with linear backoff (2s, 4s, ...) before giving up.
    """
    last_exc: Optional[BaseException] = None
    for attempt in range(1, max_attempts + 1):
        try:
            return structured_llm.invoke(prompt)
        except Exception as e:
            last_exc = e
            if attempt >= max_attempts:
                break
            wait = 2 * attempt
            try:
                st.toast(
                    f"LLM call failed ({type(e).__name__}); "
                    f"retrying in {wait}s (attempt {attempt}/{max_attempts})...",
                    icon=":material/warning:",
                )
            except Exception:
                pass
            time.sleep(wait)
    assert last_exc is not None
    raise last_exc


# --- Graph Nodes ---
def generator_node(state):
    """Generates the initial draft of the code."""
    generator_llm = get_llm().with_structured_output(DraftCode)
    prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation and an explanation.

    Request: {state['user_request']}
    """
    draft = _invoke_with_retry(generator_llm, prompt)
    return {"draft": draft.model_dump()}


def critic_node(state):
    """Critiques the generated code for errors and inefficiencies."""
    critic_llm = get_llm().with_structured_output(Critique)
    code_to_critique = state["draft"]["code"]
    prompt = f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.

    Analyze the code for:
    1.  **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
    2.  **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?

    Provide a structured critique with specific, actionable suggestions.

    Code to Review:
    ```python
    {code_to_critique}
    ```
    """
    critique = _invoke_with_retry(critic_llm, prompt)
    return {"critique": critique.model_dump()}


def refiner_node(state):
    """Refines the code based on the critique."""
    refiner_llm = get_llm().with_structured_output(RefinedCode)
    draft_code = state["draft"]["code"]
    critique_suggestions = json.dumps(state["critique"], indent=2)
    prompt = f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.

    Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.

    **Original Code:**
    ```python
    {draft_code}
    ```

    **Critique and Suggestions:**
    {critique_suggestions}

    Please provide the final, refined code and a summary of the changes you made.
    """
    refined_code = _invoke_with_retry(refiner_llm, prompt)
    return {"refined_code": refined_code.model_dump()}


# --- Build the Graph ---
@st.cache_resource(show_spinner=False)
def build_graph():
    """Compile and cache the reflection LangGraph."""
    graph_builder = StateGraph(ReflectionState)
    graph_builder.add_node("generator", generator_node)
    graph_builder.add_node("critic", critic_node)
    graph_builder.add_node("refiner", refiner_node)
    graph_builder.set_entry_point("generator")
    graph_builder.add_edge("generator", "critic")
    graph_builder.add_edge("critic", "refiner")
    graph_builder.add_edge("refiner", END)
    return graph_builder.compile()


# --- Evaluation Helper ---
def evaluate_code(code_to_evaluate: str) -> CodeEvaluation:
    """Use an LLM-as-a-judge to score the given code."""
    judge_llm = get_llm().with_structured_output(CodeEvaluation)
    prompt = f"""You are an expert judge of Python code. Evaluate the following function on a scale of 1-10 for correctness, efficiency, and style. Provide a brief justification.

    Code:
    ```python
    {code_to_evaluate}
    ```
    """
    return judge_llm.invoke(prompt)


# --- UI Helpers ---
def render_environment_sidebar() -> None:
    """Render API key / environment diagnostics in the sidebar."""
    st.sidebar.header("Environment")

    google_key = os.getenv("GOOGLE_API_KEY")
    langchain_key = os.getenv("LANGCHAIN_API_KEY")

    if google_key:
        st.sidebar.success("GOOGLE_API_KEY loaded")
    else:
        st.sidebar.error("GOOGLE_API_KEY not found. Add it to your .env file.")

    if langchain_key:
        st.sidebar.success("LANGCHAIN_API_KEY loaded (tracing enabled)")
    else:
        st.sidebar.info("LANGCHAIN_API_KEY not set (tracing disabled)")

    with st.sidebar.expander("Available Gemini models", expanded=False):
        if not google_key:
            st.write("Set GOOGLE_API_KEY to fetch the model list.")
            return
        try:
            response = requests.get(
                "https://generativelanguage.googleapis.com/v1beta/models",
                headers={"X-goog-api-key": google_key},
                timeout=10,
            )
            st.json(response.json())
        except Exception as exc:
            st.warning(f"Could not fetch models: {exc}")


def render_evaluation(label: str, evaluation: CodeEvaluation) -> None:
    """Render a CodeEvaluation block as Streamlit metrics."""
    st.subheader(label)
    cols = st.columns(3)
    cols[0].metric("Correctness", f"{evaluation.correctness_score}/10")
    cols[1].metric("Efficiency", f"{evaluation.efficiency_score}/10")
    cols[2].metric("Style", f"{evaluation.style_score}/10")
    st.write(evaluation.justification)


def render_results(final_state: ReflectionState) -> None:
    """Render the final draft, critique, refined code, and evaluations."""
    draft = final_state["draft"]
    critique = final_state["critique"]
    refined = final_state["refined_code"]

    st.header("1. Initial Draft")
    st.markdown(f"**Explanation:** {draft['explanation']}")
    st.code(draft["code"], language="python")

    st.header("2. Critique")
    st.markdown(f"**Summary:** {critique['critique_summary']}")
    badge_cols = st.columns(2)
    badge_cols[0].markdown(
        f"**Has errors:** {'Yes' if critique['has_errors'] else 'No'}"
    )
    badge_cols[1].markdown(
        f"**Efficient:** {'Yes' if critique['is_efficient'] else 'No'}"
    )
    st.markdown("**Suggested improvements:**")
    for improvement in critique["suggested_improvements"]:
        st.markdown(f"- {improvement}")

    st.header("3. Final Refined Code")
    st.markdown(f"**Refinement Summary:** {refined['refinement_summary']}")
    st.code(refined["refined_code"], language="python")

    st.header("4. LLM-as-Judge Evaluation")
    with st.spinner("Evaluating initial draft..."):
        initial_eval = evaluate_code(draft["code"])
    render_evaluation("Initial draft", initial_eval)

    with st.spinner("Evaluating refined code..."):
        refined_eval = evaluate_code(refined["refined_code"])
    render_evaluation("Refined code", refined_eval)


# --- Main Streamlit App ---
def main() -> None:
    """Streamlit entry point for the reflection workflow."""
    st.set_page_config(
        page_title="Agentic Architectures: Reflection",
        page_icon=":brain:",
        layout="wide",
    )
    st.title("Agentic Architectures: Reflection")
    st.caption("Generate a draft, critique it, and refine the code — powered by Gemini + LangGraph.")

    render_environment_sidebar()

    default_request = "Write a function that prints \"Hello, world!\""
    user_request = st.text_area(
        "What should the agent build?",
        value=default_request,
        height=160,
    )

    run = st.button("Run reflection workflow", type="primary", use_container_width=True)
    if not run:
        st.info("Enter a request above and click **Run reflection workflow** to start.")
        return

    if not os.getenv("GOOGLE_API_KEY"):
        st.error("GOOGLE_API_KEY is not set. Add it to your .env file and reload.")
        return

    reflection_app = build_graph()

    final_state: Optional[ReflectionState] = None
    step_labels = {
        "generator": "Generating initial draft",
        "critic": "Critiquing draft",
        "refiner": "Refining code",
    }

    with st.status("Running reflection workflow...", expanded=True) as status:
        status.write(f"**Request:** {user_request}")
        initial_input: ReflectionState = {
            "user_request": user_request,
            "draft": None,
            "critique": None,
            "refined_code": None,
        }

        seen_keys: set[str] = set()
        try:
            for state_update in reflection_app.stream(initial_input, stream_mode="values"):
                final_state = state_update
                for key, label in step_labels.items():
                    produced = {
                        "generator": "draft",
                        "critic": "critique",
                        "refiner": "refined_code",
                    }[key]
                    if state_update.get(produced) and key not in seen_keys:
                        seen_keys.add(key)
                        status.write(f":white_check_mark: {label}")
        except Exception as exc:
            status.update(label="Reflection workflow failed", state="error")
            st.exception(exc)
            return

        status.update(label="Reflection workflow complete", state="complete")

    if (
        final_state
        and final_state.get("draft")
        and final_state.get("critique")
        and final_state.get("refined_code")
    ):
        render_results(final_state)
    else:
        st.error("The workflow did not produce a complete result.")


if __name__ == "__main__":
    main()
