"""Agentic Architectures 1: Reflection (Flet desktop UI).

Standalone desktop port of ``01_reflection.py``. Same reflective agent
(generator -> critic -> refiner) using Google Gemini via LangChain and
LangGraph, but rendered as a native window via Flet instead of Streamlit.

The UI keeps the "belt" metaphor: each completed reflection workflow is
appended as a sealed panel containing the user request and a tabbed
assistant response (Draft / Critique / Refined / Evaluation). A persistent
input bar at the bottom feeds the next request to the belt.

Run with:
    python 01_reflection_flet.py
"""

import asyncio
import json
import os
import threading
import time
import uuid
from typing import List, Optional, TypedDict

# Silence GTK's accessibility-bridge noise on Linux.
#
# Flet renders via Flutter's Linux desktop embedder, which pulls in GTK. On
# startup GTK tries to hook the window into the AT-SPI (Assistive Technology
# Service Provider Interface) bus. If no accessibility bus is available in
# the current session (common on minimal WMs, headless runs, or plain SSH
# shells), GTK prints:
#
#     (flet:12345): Atk-CRITICAL **: atk_socket_embed:
#                   assertion 'plug_id != NULL' failed
#
# Setting NO_AT_BRIDGE=1 is the upstream-documented way to skip the AT-SPI
# bridge entirely. It does NOT affect actual screen-reader/assistive tools
# when they ARE running (they use a different code path). `setdefault` is
# used so the user can still opt back in by exporting NO_AT_BRIDGE=0.
os.environ.setdefault("NO_AT_BRIDGE", "1")

# Silence non-critical GLib debug chatter from GTK/Flutter on Linux.
#
# GLib emits messages at several levels; when G_MESSAGES_DEBUG is unset,
# GTK libs decide ad-hoc what to print. Forcing it to an empty string
# disables all debug-domain messages while still letting real warnings
# and critical errors through. Again, `setdefault` preserves any value
# the user may have set explicitly.
os.environ.setdefault("G_MESSAGES_DEBUG", "")

import flet as ft
import requests
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, StateGraph
from pydantic import BaseModel, Field


# --- API Key and Tracing Setup ---
load_dotenv(override=True)
os.environ["LANGCHAIN_TRACING_V2"] = "false"
os.environ["LANGCHAIN_PROJECT"] = "Agentic Architecture - Reflection (Gemini)"

LLM_MODEL: str = "gemini-3.1-flash-lite-preview"
LLM_TEMPERATURE: float = 0.2


# --- Pydantic Schemas ---
class DraftCode(BaseModel):
    """Schema for the initial code draft generated by the agent."""

    code: str = Field(description="The Python code generated to solve the user's request.")
    explanation: str = Field(description="A brief explanation of how the code works.")


class Critique(BaseModel):
    """Schema for the self-critique of the generated code."""

    has_errors: bool = Field(description="Does the code have any potential bugs or logical errors?")
    is_efficient: bool = Field(description="Is the code written in an efficient and optimal way?")
    suggested_improvements: List[str] = Field(
        description="Specific, actionable suggestions for improving the code."
    )
    critique_summary: str = Field(description="A summary of the critique.")


class RefinedCode(BaseModel):
    """Schema for the final, refined code after incorporating the critique."""

    refined_code: str = Field(description="The final, improved Python code.")
    refinement_summary: str = Field(
        description="A summary of the changes made based on the critique."
    )


class CodeEvaluation(BaseModel):
    """Schema for evaluating a piece of code."""

    correctness_score: int = Field(
        description="Score from 1-10 on whether the code is logically correct."
    )
    efficiency_score: int = Field(
        description="Score from 1-10 on the code's algorithmic efficiency."
    )
    style_score: int = Field(
        description="Score from 1-10 on code style and readability (PEP 8)."
    )
    justification: str = Field(description="A brief justification for the scores.")


# --- Graph State ---
class ReflectionState(TypedDict):
    """Represents the state of our reflection graph."""

    user_request: str
    draft: Optional[dict]
    critique: Optional[dict]
    refined_code: Optional[dict]


# --- LLM helpers ---
_LLM: Optional[ChatGoogleGenerativeAI] = None


def get_llm() -> ChatGoogleGenerativeAI:
    """Return a process-wide cached Gemini LLM client."""
    global _LLM
    if _LLM is None:
        _LLM = ChatGoogleGenerativeAI(
            model=LLM_MODEL, temperature=LLM_TEMPERATURE
        )
    return _LLM


def _invoke_with_retry(structured_llm, prompt: str, max_attempts: int = 3):
    """Invoke a structured LLM with small retry/backoff for transient API errors."""
    last_exc: Optional[BaseException] = None
    for attempt in range(1, max_attempts + 1):
        try:
            return structured_llm.invoke(prompt)
        except Exception as e:
            last_exc = e
            if attempt >= max_attempts:
                break
            time.sleep(2 * attempt)
    assert last_exc is not None
    raise last_exc


# --- Graph Nodes ---
def generator_node(state):
    """Generates the initial draft of the code."""
    generator_llm = get_llm().with_structured_output(DraftCode)
    prompt = f"""You are an expert Python programmer. Write a Python function to solve the following request.
    Provide a simple, clear implementation and an explanation.

    Request: {state['user_request']}
    """
    draft = _invoke_with_retry(generator_llm, prompt)
    return {"draft": draft.model_dump()}


def critic_node(state):
    """Critiques the generated code for errors and inefficiencies."""
    critic_llm = get_llm().with_structured_output(Critique)
    code_to_critique = state["draft"]["code"]
    prompt = f"""You are an expert code reviewer and senior Python developer. Your task is to perform a thorough critique of the following code.

    Analyze the code for:
    1.  **Bugs and Errors:** Are there any potential runtime errors, logical flaws, or edge cases that are not handled?
    2.  **Efficiency and Best Practices:** Is this the most efficient way to solve the problem? Does it follow standard Python conventions (PEP 8)?

    Provide a structured critique with specific, actionable suggestions.

    Code to Review:
    ```python
    {code_to_critique}
    ```
    """
    critique = _invoke_with_retry(critic_llm, prompt)
    return {"critique": critique.model_dump()}


def refiner_node(state):
    """Refines the code based on the critique."""
    refiner_llm = get_llm().with_structured_output(RefinedCode)
    draft_code = state["draft"]["code"]
    critique_suggestions = json.dumps(state["critique"], indent=2)
    prompt = f"""You are an expert Python programmer tasked with refining a piece of code based on a critique.

    Your goal is to rewrite the original code, implementing all the suggested improvements from the critique.

    **Original Code:**
    ```python
    {draft_code}
    ```

    **Critique and Suggestions:**
    {critique_suggestions}

    Please provide the final, refined code and a summary of the changes you made.
    """
    refined_code = _invoke_with_retry(refiner_llm, prompt)
    return {"refined_code": refined_code.model_dump()}


# --- Build the Graph ---
_GRAPH = None


def build_graph():
    """Compile and cache the reflection LangGraph."""
    global _GRAPH
    if _GRAPH is None:
        graph_builder = StateGraph(ReflectionState)
        graph_builder.add_node("generator", generator_node)
        graph_builder.add_node("critic", critic_node)
        graph_builder.add_node("refiner", refiner_node)
        graph_builder.set_entry_point("generator")
        graph_builder.add_edge("generator", "critic")
        graph_builder.add_edge("critic", "refiner")
        graph_builder.add_edge("refiner", END)
        _GRAPH = graph_builder.compile()
    return _GRAPH


# --- Evaluation Helper ---
def evaluate_code(code_to_evaluate: str) -> CodeEvaluation:
    """Use an LLM-as-a-judge to score the given code."""
    judge_llm = get_llm().with_structured_output(CodeEvaluation)
    prompt = f"""You are an expert judge of Python code. Evaluate the following function on a scale of 1-10 for correctness, efficiency, and style. Provide a brief justification.

    Code:
    ```python
    {code_to_evaluate}
    ```
    """
    return judge_llm.invoke(prompt)


# --- UI Building Blocks ---
MD_EXT = ft.MarkdownExtensionSet.GITHUB_FLAVORED

# Paired light/dark highlight themes. Kept in one place so they are easy to
# swap (e.g. NIGHT_OWL + GITHUB, DRACULA + ATOM_ONE_LIGHT, ...).
DARK_CODE_THEME = ft.MarkdownCodeTheme.ATOM_ONE_DARK
LIGHT_CODE_THEME = ft.MarkdownCodeTheme.GITHUB


def _is_dark_mode(page: ft.Page) -> bool:
    """Return True if the app is effectively rendering in dark mode."""
    if page.theme_mode == ft.ThemeMode.DARK:
        return True
    if page.theme_mode == ft.ThemeMode.LIGHT:
        return False
    return page.platform_brightness == ft.Brightness.DARK


def _pick_code_theme(page: ft.Page) -> ft.MarkdownCodeTheme:
    """Choose a highlight theme whose background matches the app theme."""
    return DARK_CODE_THEME if _is_dark_mode(page) else LIGHT_CODE_THEME


def _md(page: ft.Page, text: str) -> ft.Markdown:
    """Render markdown with code-block syntax highlighting."""
    return ft.Markdown(
        text,
        selectable=True,
        extension_set=MD_EXT,
        code_theme=_pick_code_theme(page),
    )


def _code_block(page: ft.Page, code: str, language: str = "python") -> ft.Markdown:
    """Render a fenced code block."""
    return _md(page, f"```{language}\n{code}\n```")


def _user_bubble(page: ft.Page, text: str) -> ft.Container:
    """Render the user's request as a chat bubble."""
    return ft.Container(
        content=ft.Row(
            controls=[
                ft.Icon(ft.Icons.PERSON, size=18),
                ft.Container(content=_md(page, text), expand=True),
            ],
            vertical_alignment=ft.CrossAxisAlignment.START,
        ),
        bgcolor=ft.Colors.with_opacity(0.08, ft.Colors.PRIMARY),
        padding=12,
        border_radius=8,
    )


def _scrollable_tab_body(controls: list[ft.Control]) -> ft.Container:
    """Wrap tab content in a fixed-height scrollable container."""
    return ft.Container(
        content=ft.Column(controls=controls, scroll=ft.ScrollMode.AUTO, spacing=8),
        height=420,
        padding=ft.Padding.only(top=8),
    )


def _metric_card(label: str, value: str) -> ft.Container:
    """Render one metric tile (correctness/efficiency/style)."""
    return ft.Container(
        content=ft.Column(
            controls=[
                ft.Text(label, size=12, color=ft.Colors.ON_SURFACE_VARIANT),
                ft.Text(value, size=22, weight=ft.FontWeight.BOLD),
            ],
            horizontal_alignment=ft.CrossAxisAlignment.CENTER,
            spacing=2,
        ),
        bgcolor=ft.Colors.with_opacity(0.05, ft.Colors.PRIMARY),
        padding=12,
        border_radius=8,
        expand=True,
    )


def _evaluation_block(label: str, evaluation: dict) -> ft.Column:
    """Render a CodeEvaluation dict as three metric tiles + justification."""
    return ft.Column(
        controls=[
            ft.Text(label, weight=ft.FontWeight.BOLD, size=14),
            ft.Row(
                controls=[
                    _metric_card("Correctness", f"{evaluation['correctness_score']}/10"),
                    _metric_card("Efficiency", f"{evaluation['efficiency_score']}/10"),
                    _metric_card("Style", f"{evaluation['style_score']}/10"),
                ],
                spacing=10,
            ),
            ft.Text(evaluation["justification"]),
        ],
        spacing=8,
    )


def _build_completed_card(page: ft.Page, index: int, turn: dict) -> ft.Card:
    """Render a single completed reflection run as a sealed belt panel."""
    request = turn["user_request"]
    final_state = turn["final_state"]
    draft = final_state["draft"]
    critique = final_state["critique"]
    refined = final_state["refined_code"]

    draft_tab = _scrollable_tab_body(
        [
            _md(page, f"**Explanation:** {draft['explanation']}"),
            _code_block(page, draft["code"]),
        ]
    )

    suggestions_md = "\n".join(f"- {s}" for s in critique["suggested_improvements"])
    critique_tab = _scrollable_tab_body(
        [
            _md(page, f"**Summary:** {critique['critique_summary']}"),
            ft.Row(
                controls=[
                    _md(page, f"**Has errors:** {'Yes' if critique['has_errors'] else 'No'}"),
                    _md(page, f"**Efficient:** {'Yes' if critique['is_efficient'] else 'No'}"),
                ],
                spacing=20,
            ),
            _md(page, "**Suggested improvements:**\n" + suggestions_md),
        ]
    )

    refined_tab = _scrollable_tab_body(
        [
            _md(page, f"**Refinement Summary:** {refined['refinement_summary']}"),
            _code_block(page, refined["refined_code"]),
        ]
    )

    eval_tab = _scrollable_tab_body(
        [
            _evaluation_block("Initial draft", turn["initial_eval"]),
            ft.Divider(),
            _evaluation_block("Refined code", turn["refined_eval"]),
        ]
    )

    tab_bar = ft.TabBar(
        tabs=[
            ft.Tab(label="1. Draft"),
            ft.Tab(label="2. Critique"),
            ft.Tab(label="3. Refined"),
            ft.Tab(label="4. Evaluation"),
        ],
    )
    tab_view = ft.TabBarView(
        controls=[draft_tab, critique_tab, refined_tab, eval_tab],
        expand=True,
    )
    tabs = ft.Tabs(
        length=4,
        selected_index=0,
        content=ft.Column(controls=[tab_bar, tab_view], expand=True, spacing=0),
    )

    return ft.Card(
        content=ft.Container(
            content=ft.Column(
                controls=[
                    ft.Text(f"Run #{index + 1}", weight=ft.FontWeight.BOLD, size=18),
                    _user_bubble(page, request),
                    ft.Container(content=tabs, height=520),
                ],
                spacing=10,
            ),
            padding=15,
        ),
    )


def _build_failed_card(page: ft.Page, index: int, turn: dict) -> ft.Card:
    """Render a turn that failed during the reflection workflow."""
    return ft.Card(
        content=ft.Container(
            content=ft.Column(
                controls=[
                    ft.Text(f"Run #{index + 1}", weight=ft.FontWeight.BOLD, size=18),
                    _user_bubble(page, turn["user_request"]),
                    ft.Container(
                        content=ft.Row(
                            controls=[
                                ft.Icon(ft.Icons.ERROR, color=ft.Colors.ERROR),
                                ft.Text(
                                    turn.get(
                                        "error",
                                        "The workflow did not produce a complete result.",
                                    ),
                                    color=ft.Colors.ERROR,
                                    selectable=True,
                                ),
                            ],
                            spacing=8,
                        ),
                        padding=10,
                        bgcolor=ft.Colors.with_opacity(0.08, ft.Colors.ERROR),
                        border_radius=8,
                    ),
                ],
                spacing=10,
            ),
            padding=15,
        ),
    )


# --- Async workflow runner ---
async def _run_reflection_workflow(
    user_request: str,
    status_column: ft.Column,
    page: ft.Page,
):
    """Drive the LangGraph workflow and stream node completions into the UI."""
    graph = build_graph()
    initial_input: ReflectionState = {
        "user_request": user_request,
        "draft": None,
        "critique": None,
        "refined_code": None,
    }

    step_labels = {
        "generator": "Generated initial draft",
        "critic": "Critiqued draft",
        "refiner": "Refined code",
    }
    produced_by = {
        "generator": "draft",
        "critic": "critique",
        "refiner": "refined_code",
    }

    queue: asyncio.Queue = asyncio.Queue()
    loop = asyncio.get_running_loop()

    def worker():
        try:
            for state_update in graph.stream(initial_input, stream_mode="values"):
                loop.call_soon_threadsafe(queue.put_nowait, ("update", state_update))
            loop.call_soon_threadsafe(queue.put_nowait, ("done", None))
        except Exception as exc:
            loop.call_soon_threadsafe(queue.put_nowait, ("error", exc))

    threading.Thread(target=worker, daemon=True).start()

    final_state: Optional[ReflectionState] = None
    seen: set[str] = set()

    while True:
        kind, payload = await queue.get()
        if kind == "update":
            final_state = payload
            for key, label in step_labels.items():
                if final_state and final_state.get(produced_by[key]) and key not in seen:
                    seen.add(key)
                    status_column.controls.append(
                        ft.Row(
                            controls=[
                                ft.Icon(ft.Icons.CHECK_CIRCLE, color=ft.Colors.GREEN),
                                ft.Text(label),
                            ],
                            spacing=8,
                        )
                    )
                    page.update()
        elif kind == "error":
            raise payload
        elif kind == "done":
            break

    if not (
        final_state
        and final_state.get("draft")
        and final_state.get("critique")
        and final_state.get("refined_code")
    ):
        raise RuntimeError("The workflow did not produce a complete result.")

    status_column.controls.append(
        ft.Row(
            controls=[
                ft.ProgressRing(width=14, height=14, stroke_width=2),
                ft.Text("Evaluating initial draft..."),
            ],
            spacing=8,
        )
    )
    page.update()
    initial_eval = await asyncio.to_thread(evaluate_code, final_state["draft"]["code"])

    status_column.controls.append(
        ft.Row(
            controls=[
                ft.ProgressRing(width=14, height=14, stroke_width=2),
                ft.Text("Evaluating refined code..."),
            ],
            spacing=8,
        )
    )
    page.update()
    refined_eval = await asyncio.to_thread(
        evaluate_code, final_state["refined_code"]["refined_code"]
    )

    return final_state, initial_eval.model_dump(), refined_eval.model_dump()


# --- Sidebar ---
def _build_sidebar(
    page: ft.Page,
    turns: list[dict],
    belt: ft.Column,
    empty_hint: ft.Control,
) -> ft.Column:
    """Build the left sidebar with environment + belt diagnostics."""
    google_key = os.getenv("GOOGLE_API_KEY")
    langchain_key = os.getenv("LANGCHAIN_API_KEY")

    if google_key:
        google_status = ft.Row(
            controls=[
                ft.Icon(ft.Icons.CHECK_CIRCLE, color=ft.Colors.GREEN, size=18),
                ft.Text("GOOGLE_API_KEY loaded"),
            ],
            spacing=6,
        )
    else:
        google_status = ft.Row(
            controls=[
                ft.Icon(ft.Icons.ERROR, color=ft.Colors.RED, size=18),
                ft.Text("GOOGLE_API_KEY not found", color=ft.Colors.RED),
            ],
            spacing=6,
        )

    if langchain_key:
        langchain_status = ft.Row(
            controls=[
                ft.Icon(ft.Icons.CHECK_CIRCLE, color=ft.Colors.GREEN, size=18),
                ft.Text("LANGCHAIN_API_KEY loaded"),
            ],
            spacing=6,
        )
    else:
        langchain_status = ft.Row(
            controls=[
                ft.Icon(ft.Icons.INFO, color=ft.Colors.BLUE, size=18),
                ft.Text("LANGCHAIN_API_KEY not set"),
            ],
            spacing=6,
        )

    completed_label = ft.Text(_completed_label_text(turns))

    def clear_belt(_):
        turns.clear()
        belt.controls.clear()
        belt.controls.append(empty_hint)
        completed_label.value = _completed_label_text(turns)
        page.update()

    clear_btn = ft.Button(
        "Clear belt",
        icon=ft.Icons.DELETE_SWEEP,
        on_click=clear_belt,
    )

    def show_models(_):
        if not google_key:
            page.show_dialog(
                ft.AlertDialog(
                    title=ft.Text("Models unavailable"),
                    content=ft.Text("Set GOOGLE_API_KEY to fetch the model list."),
                )
            )
            return
        try:
            response = requests.get(
                "https://generativelanguage.googleapis.com/v1beta/models",
                headers={"X-goog-api-key": google_key},
                timeout=10,
            )
            body = json.dumps(response.json(), indent=2)
        except Exception as exc:
            body = f"Could not fetch models: {exc}"

        dlg = ft.AlertDialog(
            title=ft.Text("Available Gemini models"),
            content=ft.Container(
                content=ft.Column(
                    controls=[ft.Text(body, selectable=True, font_family="monospace")],
                    scroll=ft.ScrollMode.AUTO,
                ),
                width=600,
                height=500,
            ),
            actions=[ft.TextButton("Close", on_click=lambda e: page.pop_dialog())],
        )
        page.show_dialog(dlg)

    models_btn = ft.OutlinedButton(
        "Available Gemini models",
        icon=ft.Icons.LIST,
        on_click=show_models,
    )

    sidebar = ft.Column(
        controls=[
            ft.Text("Environment", weight=ft.FontWeight.BOLD, size=16),
            google_status,
            langchain_status,
            ft.Divider(),
            ft.Text("Belt", weight=ft.FontWeight.BOLD, size=16),
            completed_label,
            clear_btn,
            ft.Divider(),
            models_btn,
        ],
        spacing=10,
        scroll=ft.ScrollMode.AUTO,
        expand=True,
    )

    sidebar.completed_label = completed_label  # type: ignore[attr-defined]
    return sidebar


def _completed_label_text(turns: list[dict]) -> str:
    completed = sum(1 for t in turns if t.get("status") == "complete")
    return f"Completed runs on belt: {completed}"


# --- Main Flet App ---
async def main(page: ft.Page):
    """Flet entry point for the reflection desktop app."""
    page.title = "Agentic Architectures: Reflection"
    page.theme_mode = ft.ThemeMode.SYSTEM
    page.padding = 0
    page.window.width = 1280
    page.window.height = 860

    turns: list[dict] = []

    empty_hint = ft.Container(
        content=ft.Row(
            controls=[
                ft.Icon(ft.Icons.INFO_OUTLINE, color=ft.Colors.BLUE),
                ft.Text(
                    "Send a request below to start the reflection belt.",
                    italic=True,
                ),
            ],
            spacing=8,
        ),
        padding=20,
        bgcolor=ft.Colors.with_opacity(0.06, ft.Colors.PRIMARY),
        border_radius=8,
    )

    belt = ft.Column(
        controls=[empty_hint],
        spacing=15,
        scroll=ft.ScrollMode.AUTO,
        expand=True,
        auto_scroll=True,
    )

    sidebar = _build_sidebar(page, turns, belt, empty_hint)

    input_field = ft.TextField(
        hint_text="What should the agent build?",
        expand=True,
        autofocus=True,
        shift_enter=True,
        min_lines=1,
        max_lines=4,
    )
    send_btn = ft.IconButton(
        icon=ft.Icons.SEND,
        tooltip="Send request",
        icon_size=22,
    )

    async def submit(_=None):
        text = (input_field.value or "").strip()
        if not text:
            return
        if not os.getenv("GOOGLE_API_KEY"):
            page.show_dialog(
                ft.AlertDialog(
                    title=ft.Text("Missing API key"),
                    content=ft.Text(
                        "GOOGLE_API_KEY is not set. Add it to your .env file and restart."
                    ),
                )
            )
            return

        input_field.value = ""
        input_field.disabled = True
        send_btn.disabled = True
        page.update()

        index = len(turns)
        turn = {
            "id": uuid.uuid4().hex,
            "user_request": text,
            "status": "pending",
        }
        turns.append(turn)

        if empty_hint in belt.controls:
            belt.controls.remove(empty_hint)

        status_column = ft.Column(
            controls=[
                ft.Row(
                    controls=[
                        ft.ProgressRing(width=16, height=16, stroke_width=2),
                        ft.Text("Running reflection workflow..."),
                    ],
                    spacing=8,
                ),
            ],
            spacing=6,
        )
        pending_card = ft.Card(
            content=ft.Container(
                content=ft.Column(
                    controls=[
                        ft.Text(
                            f"Run #{index + 1}",
                            weight=ft.FontWeight.BOLD,
                            size=18,
                        ),
                        _user_bubble(page, text),
                        status_column,
                    ],
                    spacing=10,
                ),
                padding=15,
            )
        )
        belt.controls.append(pending_card)
        page.update()

        try:
            final_state, initial_eval, refined_eval = await _run_reflection_workflow(
                text, status_column, page
            )
            turn["final_state"] = final_state
            turn["initial_eval"] = initial_eval
            turn["refined_eval"] = refined_eval
            turn["status"] = "complete"
            idx = belt.controls.index(pending_card)
            belt.controls[idx] = _build_completed_card(page, index, turn)
        except Exception as exc:
            turn["status"] = "failed"
            turn["error"] = f"{type(exc).__name__}: {exc}"
            idx = belt.controls.index(pending_card)
            belt.controls[idx] = _build_failed_card(page, index, turn)
        finally:
            sidebar.completed_label.value = _completed_label_text(turns)  # type: ignore[attr-defined]
            input_field.disabled = False
            send_btn.disabled = False
            page.update()
            await input_field.focus()

    input_field.on_submit = submit
    send_btn.on_click = submit

    input_bar = ft.Container(
        content=ft.Row(
            controls=[input_field, send_btn],
            vertical_alignment=ft.CrossAxisAlignment.END,
            spacing=8,
        ),
        padding=12,
        bgcolor=ft.Colors.with_opacity(0.04, ft.Colors.PRIMARY),
        border=ft.Border.only(top=ft.BorderSide(1, ft.Colors.OUTLINE_VARIANT)),
    )

    header = ft.Container(
        content=ft.Column(
            controls=[
                ft.Text(
                    "Agentic Architectures: Reflection",
                    size=22,
                    weight=ft.FontWeight.BOLD,
                ),
                ft.Text(
                    "Each request becomes a sealed panel on the belt — generate, "
                    "critique, refine. Powered by Gemini + LangGraph.",
                    italic=True,
                    color=ft.Colors.ON_SURFACE_VARIANT,
                ),
            ],
            spacing=4,
        ),
        padding=ft.Padding.only(left=15, right=15, top=15, bottom=5),
    )

    main_area = ft.Column(
        controls=[
            header,
            ft.Container(content=belt, padding=15, expand=True),
            input_bar,
        ],
        expand=True,
        spacing=0,
    )

    sidebar_container = ft.Container(
        content=sidebar,
        width=300,
        padding=15,
        bgcolor=ft.Colors.with_opacity(0.04, ft.Colors.ON_SURFACE),
    )

    page.add(
        ft.Row(
            controls=[
                sidebar_container,
                ft.VerticalDivider(width=1),
                ft.Container(content=main_area, expand=True),
            ],
            expand=True,
            spacing=0,
            vertical_alignment=ft.CrossAxisAlignment.STRETCH,
        )
    )

    if not os.getenv("GOOGLE_API_KEY"):
        page.show_dialog(
            ft.AlertDialog(
                title=ft.Text("Missing API key"),
                content=ft.Text(
                    "GOOGLE_API_KEY is not set. Add it to your .env file and restart."
                ),
            )
        )


if __name__ == "__main__":
    ft.run(main)
